"""Vocabulary tables salvaged from the April-2026 bulk-classification one-shot.

Source files (deleted in commit 3; see git history):
  - WIKI_CONCEPTS, TAG_TRIGGERS, RISK_TRIGGERS — scripts/classify.py (lines 27, 131, 238)
  - KEEP_UPPER_ACRONYMS                        — scripts/audit_frontmatter.py (line 56)

Lifted verbatim. Type annotations added on top; bodies unchanged.
"""

WIKI_CONCEPTS: dict[str, list[str]] = {
    "RLHF & Its Limitations": [
        "rlhf",
        "reinforcement learning from human feedback",
        "reward model",
        "reward hacking",
        "preference learning",
        "human feedback",
        "ppo",
        "instructgpt",
        "reward modeling",
    ],
    "Constitutional AI (RLAIF)": [
        "constitutional ai",
        "constitutional-ai",
        "rlaif",
        "ai feedback",
        "principle-based",
        "self-critique",
    ],
    "Scalable Oversight": [
        "scalable oversight",
        "debate",
        "iterated amplification",
        "ida",
        "recursive reward modeling",
        "factored cognition",
        "weak-to-strong",
    ],
    "Alignment Faking & Scheming": [
        "alignment faking",
        "scheming",
        "deceptive alignment",
        "sleeper agent",
        "sandbagging",
        "strategic compliance",
        "deception",
    ],
    "Weak-to-Strong Generalization": [
        "weak-to-strong",
        "weak to strong",
        "w2sg",
        "superalignment",
        "eliciting latent knowledge",
        "elk",
    ],
    "Agentic Misalignment": [
        "agentic",
        "tool use",
        "tool-using",
        "multi-agent",
        "agent scaffolding",
        "autonomous agent",
        "agent safety",
    ],
    "Existential Risk & Superintelligence": [
        "existential risk",
        "x-risk",
        "superintelligence",
        "agi",
        "intelligence explosion",
        "control problem",
        "extinction",
        "transformative ai",
        "rogue ai",
    ],
    "Pretraining Data Filtering": [
        "data filtering",
        "pretraining filter",
        "data curation",
        "unlearning",
        "safety filtering",
    ],
    "AI Evaluations & Benchmarks": [
        "evaluation",
        "benchmark",
        "eval",
        "red team",
        "red-team",
        "red-teaming",
        "dangerous capabilit",
        "capability elicitation",
        "science of evals",
        "metr",
        "apollo research",
    ],
    "Responsible Scaling Policies": [
        "responsible scaling",
        "rsp",
        "asl",
        "deployment gate",
        "capability threshold",
        "model card",
        "scaling policy",
    ],
    "AI Lab Safety Scorecards": [
        "lab scorecard",
        "ai lab watch",
        "safety scorecard",
        "lab safety",
    ],
}

TAG_TRIGGERS: dict[str, list[str]] = {
    # alignment & safety
    "alignment-faking": ["alignment faking", "alignment-faking"],
    "scheming": ["scheming"],
    "deception": ["deception", "deceptive"],
    "deceptive-alignment": ["deceptive alignment"],
    "sleeper-agents": ["sleeper agent", "sleeper-agent"],
    "sandbagging": ["sandbagging"],
    "sycophancy": ["sycophan"],
    "shutdown-resistance": ["shutdown"],
    "corrigibility": ["corrigib"],
    "inner-alignment": ["inner alignment"],
    "outer-alignment": ["outer alignment"],
    "mesa-optimization": ["mesa-optim", "mesa optim"],
    "goal-misgeneralization": ["goal misgeneralization", "goal misgen"],
    "power-seeking": ["power-seeking", "power seeking"],
    "instrumental-convergence": ["instrumental converg"],
    # training
    "RLHF": ["rlhf"],
    "RLAIF": ["rlaif"],
    "Constitutional-AI": ["constitutional ai", "constitutional-ai"],
    "reward-hacking": ["reward hacking", "reward-hacking"],
    "reward-modeling": ["reward model"],
    "PPO": ["ppo "],
    "DPO": ["dpo "],
    "process-supervision": ["process supervision", "process-supervision"],
    "outcome-supervision": ["outcome supervision"],
    "deliberative-alignment": ["deliberative alignment"],
    "scalable-oversight": ["scalable oversight"],
    "debate": ["debate "],
    "IDA": ["iterated amplification", " ida "],
    "recursive-reward-modeling": ["recursive reward"],
    "W2SG": ["w2sg", "weak-to-strong", "weak to strong"],
    "weak-to-strong": ["weak-to-strong", "weak to strong"],
    "superalignment": ["superalignment"],
    "pretraining-filtering": ["pretraining filter", "data filtering"],
    "data-filtering": ["data filtering"],
    "unlearning": ["unlearning"],
    # evaluation
    "evaluations": ["evaluation"],
    "benchmarks": ["benchmark"],
    "red-teaming": ["red team", "red-team"],
    "dangerous-capabilities": ["dangerous capabilit"],
    "science-of-evals": ["science of eval"],
    "capability-elicitation": ["capability elicit"],
    "sandbagging-evals": ["sandbagging eval"],
    "CoT-monitoring": ["chain-of-thought monitor", "cot monitor"],
    "chain-of-thought": ["chain-of-thought", "chain of thought"],
    # risk domains
    "biorisk": ["biorisk", "biological risk", "bioterror"],
    "bioweapons": ["bioweapon", "biological weapon"],
    "cyber-offense": ["cyber offense", "cyberoffense", "cyber-offense", "cybersecur"],
    "CSAM": ["csam", "child sexual"],
    "CBRN": ["cbrn"],
    "disinformation": ["disinformation", "misinformation"],
    "persuasion": ["persuasion"],
    "dual-use": ["dual-use", "dual use"],
    # governance
    "RSP": ["responsible scaling", "rsp"],
    "responsible-scaling": ["responsible scaling"],
    "ASL": ["asl-", "asl ", "ai safety level"],
    "deployment-gates": ["deployment gate"],
    "model-card": ["model card", "system card"],
    "lab-scorecard": ["lab scorecard", "ai lab watch"],
    "safety-cases": ["safety case"],
    "governance": ["governance"],
    "regulation": ["regulation", "regulatory"],
    "international-coordination": ["international coordination", "international cooperation"],
    "compute-governance": ["compute governance"],
    # x-risk
    "x-risk": ["x-risk"],
    "existential-risk": ["existential risk"],
    "superintelligence": ["superintelligence"],
    "AGI": [" agi "],
    "intelligence-explosion": ["intelligence explosion"],
    "control-problem": ["control problem"],
    "catastrophic-risk": ["catastrophic risk", "catastrophic"],
    "extinction": ["extinction"],
    # agents
    "agentic-AI": ["agentic"],
    "multi-agent": ["multi-agent", "multi agent"],
    "tool-use": ["tool use", "tool-use"],
    "agent-scaffolding": ["agent scaffold"],
    "autonomous-systems": ["autonomous"],
    # orgs
    "Anthropic": ["anthropic"],
    "OpenAI": ["openai"],
    "DeepMind": ["deepmind"],
    "Google": ["google "],
    "Meta": [" meta "],
    "MIRI": ["miri "],
    "ARC": ["arc evals", "alignment research center"],
    "METR": ["metr "],
    # misc
    "interpretability": ["interpretab"],
    "mechanistic-interpretability": ["mechanistic interpretab"],
    "transparency": ["transparency"],
    "robustness": ["robustness"],
    "adversarial": ["adversarial"],
    "jailbreaking": ["jailbreak"],
    "prompt-injection": ["prompt injection"],
    "watermarking": ["watermark"],
    "open-source": ["open source", "open-source"],
    "open-weight": ["open weight", "open-weight"],
}

RISK_TRIGGERS: dict[str, list[str]] = {
    "misuse": [
        "bioweapon",
        "biorisk",
        "biological risk",
        "cbrn",
        "cyber offense",
        "cyber-offense",
        "cyber attack",
        "cybersecur",
        "csam",
        "disinformation",
        "misinformation",
        "persuasion",
        "jailbreak",
        "dual-use",
        "dual use",
        "uplift",
        "weaponiz",
        "malicious use",
    ],
    "misalignment": [
        "alignment faking",
        "scheming",
        "deceptive alignment",
        "sleeper agent",
        "sandbagging",
        "reward hacking",
        "power-seeking",
        "power seeking",
        "instrumental converg",
        "shutdown resistance",
        "corrigib",
        "deception",
        "mesa-optim",
        "goal misgen",
        "inner alignment",
        "outer alignment",
        "deceptive ai",
        "alignment-faking",
    ],
    "mistakes": [
        "hallucination",
        "overreliance",
        "distributional shift",
        "high-stakes",
        "high stakes",
    ],
    "structural": [
        "concentration of power",
        "structural risk",
        "economic disruption",
        "epistemic risk",
        "labor displace",
        "automation risk",
        "geopolitic",
        "concentration",
        "erosion of oversight",
    ],
}

KEEP_UPPER_ACRONYMS: set[str] = {
    "AI",
    "ML",
    "AGI",
    "RLHF",
    "RLAIF",
    "ASL",
    "RSP",
    "LLM",
    "GPU",
    "TPU",
    "API",
    "CSAM",
    "CBRN",
    "ELK",
    "W2SG",
    "IDA",
    "PPO",
    "DPO",
    "METR",
    "ARC",
    "FAQ",
    "OOM",
    "OOMs",
    "MIRI",
    "ROME",
    "MMLU",
    "BIG",
    "BBQ",
    "LTBT",
    "CAI",
    "RM",
    "RMs",
    "PDF",
    "URL",
    "ICLR",
    "NeurIPS",
    "ICML",
    "EMNLP",
    "AAAI",
    "JMLR",
    "CSAIL",
    "WMDP",
    "VCT",
    "CSIS",
    "CISA",
    "NCSC",
    "DeepMind",
    "OpenAI",
    "ARCHES",
    "FLI",
    "FSF",
    "DCLM",
    "ATLAS",
    "SCIF",
    "GPT-4",
    "GPT-3",
    "GPT-2",
    "GPT-OSS",
    "RAND",
    "CAIS",
    "FMF",
    "MATS",
    "AISI",
}
